# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 715cf7bf181d7933956ef38b2abaad430c7fc39b15379274de11e7712ed17417918000f40d53a6d175f31c212eb1a94df5c0d5432c6ff813e3a06da74568d1c7

test:
  secret_key_base: e8e4c8a79f6e3dd9b35f94e74a525b9d958fbf450b7ebea93a4c0bbee8a365f8378a08b6bdf782de910c19d1c91ad54ec0d88585f0d7ed068984b7219922d686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
